name: Manual Build

on:
  workflow_dispatch:
    inputs:
    # Git 참조(브랜치/태그)를 선택할 수 있는 드롭다운 메뉴
      git_ref:
        description: '빌드할 브랜치 또는 태그를 선택하세요.'
        required: true
        type: choice
        default: 'main'
        options:
          - main
          - develop

jobs:
  call-build:
    # 재사용 가능한 워크플로를 호출합니다.
    uses: ./.github/workflows/reusable-build.yml
    with:
      # 사용자가 입력한 git_ref 값을 빌드 대상으로 전달합니다.
      git_ref: ${{ github.event.inputs.git_ref }}
    secrets: inherit # 호출하는 워크플로의 secrets을 그대로 상속하여 전달합니다.
