name: Manual Build

on:
  workflow_dispatch:
    inputs:
    # Git 참조(브랜치/태그)를 선택할 수 있는 드롭다운 메뉴
      git_ref:
        description: '빌드할 브랜치 또는 태그를 선택하세요.'
        required: true
        type: choice
        default: 'main'
        options:
          - main
          - develop

jobs:
  call-test:
    permissions:
      checks: write # Checks, PR에 메시지 등록 권한
      pull-requests: write

    # 재사용 가능한 test Workflow를 호출
    uses: ./.github/workflows/reusable-test.yaml
    with:
      # PR의 HEAD 커밋 ref를 빌드 대상으로 전달
      git_ref: ${{ github.pull_request.head.sha }}
    secrets: inherit # 호출하는 Workflow의 secrets을 그대로 상속하여 전달

  call-build:
    # 재사용 가능한 build Workflow를 호출
    uses: ./.github/workflows/reusable-build.yaml
    with:
      # PR의 HEAD 커밋 ref를 빌드 대상으로 전달
      git_ref: ${{ github.pull_request.head.sha }}
    secrets: inherit # 호출하는 Workflow의 secrets을 그대로 상속하여 전달
