name: Reusable Android Build Job

on:
  # 다른 Workflow에서 호출할 수 있도록 정의
  workflow_call:
    inputs:
      # 체크아웃할 브랜치 또는 태그를 입력으로 받음
      git_ref:
        required: true
        type: string

jobs:
  test:
    runs-on: runner1 # Runner 이름으로 Workflow를 수행할 Runner 선택
    permissions:
      checks: write # Checks, PR에 메시지 등록 권한
      pull-requests: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4 # 저장소 코드를 체크아웃
        with:
          ref: ${{ inputs.git_ref }} # 입력으로 받은 git_ref를 사용

      - name: Setup JDK 21
        uses: actions/setup-java@v4 # Java 환경 설정 Action 사용
        with:
          distribution: 'temurin' # OpenJDK 사용
          java-version: '21' # JDK 21 버전 사용

      - name: Setup Android SDK
        # Android SDK 및 라이센스 설정을 위한 Action
        uses: android-actions/setup-android@v3

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew # gradlew 스크립트에 실행 권한 부여

      - name: Test
        # Gradle Wrapper를 사용하여 testRelease 태스크 실행
        run: ./gradlew testRelease

#      - name: Setup Python
#        uses: actions/setup-python@v6
#        with:
#          python-version: '3.13'

      - name: Publish Test Results
        uses: EnricoMi/publish-unit-test-result-action/linux@v2 # 테스트 리포트 등록
        if: (!cancelled())
        with:
          files: |
            **/build/test-results/testReleaseUnitTest/**/*.xml
